<?xml version="1.0" encoding="utf-8"?><Database Name="NUMBDATABASE" Class="NUMBDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(localdb)\v12.0;Initial Catalog=NUMBDATABASE;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="NUMBDATABASEConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Client" Member="Clients">
    <Type Name="Client">
      <Column Name="Client_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Surname" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Contacts" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Address1" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Address2" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Province" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ZipCode" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Product" Member="Products">
    <Type Name="Product">
      <Column Name="Product_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Category" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>