//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalWeb.TechService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/Techno_Service")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char activeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string address1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string address2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contacsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string provinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string surnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode {
            get {
                return this.ZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipCodeField, value) != true)) {
                    this.ZipCodeField = value;
                    this.RaisePropertyChanged("ZipCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char active {
            get {
                return this.activeField;
            }
            set {
                if ((this.activeField.Equals(value) != true)) {
                    this.activeField = value;
                    this.RaisePropertyChanged("active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string address1 {
            get {
                return this.address1Field;
            }
            set {
                if ((object.ReferenceEquals(this.address1Field, value) != true)) {
                    this.address1Field = value;
                    this.RaisePropertyChanged("address1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string address2 {
            get {
                return this.address2Field;
            }
            set {
                if ((object.ReferenceEquals(this.address2Field, value) != true)) {
                    this.address2Field = value;
                    this.RaisePropertyChanged("address2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string city {
            get {
                return this.cityField;
            }
            set {
                if ((object.ReferenceEquals(this.cityField, value) != true)) {
                    this.cityField = value;
                    this.RaisePropertyChanged("city");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contacs {
            get {
                return this.contacsField;
            }
            set {
                if ((object.ReferenceEquals(this.contacsField, value) != true)) {
                    this.contacsField = value;
                    this.RaisePropertyChanged("contacs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string province {
            get {
                return this.provinceField;
            }
            set {
                if ((object.ReferenceEquals(this.provinceField, value) != true)) {
                    this.provinceField = value;
                    this.RaisePropertyChanged("province");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string surname {
            get {
                return this.surnameField;
            }
            set {
                if ((object.ReferenceEquals(this.surnameField, value) != true)) {
                    this.surnameField = value;
                    this.RaisePropertyChanged("surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                if ((object.ReferenceEquals(this.typeField, value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductD", Namespace="http://schemas.datacontract.org/2004/07/Techno_Service")]
    [System.SerializableAttribute()]
    public partial class ProductD : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char activeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string brandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string categoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal discountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string image_urlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string manufactureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int quantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char active {
            get {
                return this.activeField;
            }
            set {
                if ((this.activeField.Equals(value) != true)) {
                    this.activeField = value;
                    this.RaisePropertyChanged("active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string brand {
            get {
                return this.brandField;
            }
            set {
                if ((object.ReferenceEquals(this.brandField, value) != true)) {
                    this.brandField = value;
                    this.RaisePropertyChanged("brand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string category {
            get {
                return this.categoryField;
            }
            set {
                if ((object.ReferenceEquals(this.categoryField, value) != true)) {
                    this.categoryField = value;
                    this.RaisePropertyChanged("category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal discount {
            get {
                return this.discountField;
            }
            set {
                if ((this.discountField.Equals(value) != true)) {
                    this.discountField = value;
                    this.RaisePropertyChanged("discount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string image_url {
            get {
                return this.image_urlField;
            }
            set {
                if ((object.ReferenceEquals(this.image_urlField, value) != true)) {
                    this.image_urlField = value;
                    this.RaisePropertyChanged("image_url");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string manufacture {
            get {
                return this.manufactureField;
            }
            set {
                if ((object.ReferenceEquals(this.manufactureField, value) != true)) {
                    this.manufactureField = value;
                    this.RaisePropertyChanged("manufacture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int quantity {
            get {
                return this.quantityField;
            }
            set {
                if ((this.quantityField.Equals(value) != true)) {
                    this.quantityField = value;
                    this.RaisePropertyChanged("quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CartClass", Namespace="http://schemas.datacontract.org/2004/07/Techno_Service")]
    [System.SerializableAttribute()]
    public partial class CartClass : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CartIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string image_urlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string productDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int productIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string productNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double unitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int userIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CartId {
            get {
                return this.CartIdField;
            }
            set {
                if ((this.CartIdField.Equals(value) != true)) {
                    this.CartIdField = value;
                    this.RaisePropertyChanged("CartId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Qty {
            get {
                return this.QtyField;
            }
            set {
                if ((this.QtyField.Equals(value) != true)) {
                    this.QtyField = value;
                    this.RaisePropertyChanged("Qty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string image_url {
            get {
                return this.image_urlField;
            }
            set {
                if ((object.ReferenceEquals(this.image_urlField, value) != true)) {
                    this.image_urlField = value;
                    this.RaisePropertyChanged("image_url");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string productDescription {
            get {
                return this.productDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.productDescriptionField, value) != true)) {
                    this.productDescriptionField = value;
                    this.RaisePropertyChanged("productDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int productId {
            get {
                return this.productIdField;
            }
            set {
                if ((this.productIdField.Equals(value) != true)) {
                    this.productIdField = value;
                    this.RaisePropertyChanged("productId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string productName {
            get {
                return this.productNameField;
            }
            set {
                if ((object.ReferenceEquals(this.productNameField, value) != true)) {
                    this.productNameField = value;
                    this.RaisePropertyChanged("productName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double unit {
            get {
                return this.unitField;
            }
            set {
                if ((this.unitField.Equals(value) != true)) {
                    this.unitField = value;
                    this.RaisePropertyChanged("unit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int userId {
            get {
                return this.userIdField;
            }
            set {
                if ((this.userIdField.Equals(value) != true)) {
                    this.userIdField = value;
                    this.RaisePropertyChanged("userId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TechService.ITechno_service")]
    public interface ITechno_service {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechno_service/UserRegister", ReplyAction="http://tempuri.org/ITechno_service/UserRegisterResponse")]
        bool UserRegister(FinalWeb.TechService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechno_service/UserRegister", ReplyAction="http://tempuri.org/ITechno_service/UserRegisterResponse")]
        System.Threading.Tasks.Task<bool> UserRegisterAsync(FinalWeb.TechService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechno_service/Login", ReplyAction="http://tempuri.org/ITechno_service/LoginResponse")]
        bool Login(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechno_service/Login", ReplyAction="http://tempuri.org/ITechno_service/LoginResponse")]
        System.Threading.Tasks.Task<bool> LoginAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechno_service/userinfor_Retrieval", ReplyAction="http://tempuri.org/ITechno_service/userinfor_RetrievalResponse")]
        FinalWeb.TechService.User userinfor_Retrieval(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechno_service/userinfor_Retrieval", ReplyAction="http://tempuri.org/ITechno_service/userinfor_RetrievalResponse")]
        System.Threading.Tasks.Task<FinalWeb.TechService.User> userinfor_RetrievalAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechno_service/userinfor_Retrieval_Email", ReplyAction="http://tempuri.org/ITechno_service/userinfor_Retrieval_EmailResponse")]
        FinalWeb.TechService.User userinfor_Retrieval_Email(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechno_service/userinfor_Retrieval_Email", ReplyAction="http://tempuri.org/ITechno_service/userinfor_Retrieval_EmailResponse")]
        System.Threading.Tasks.Task<FinalWeb.TechService.User> userinfor_Retrieval_EmailAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechno_service/resetPass", ReplyAction="http://tempuri.org/ITechno_service/resetPassResponse")]
        bool resetPass(int email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechno_service/resetPass", ReplyAction="http://tempuri.org/ITechno_service/resetPassResponse")]
        System.Threading.Tasks.Task<bool> resetPassAsync(int email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechno_service/updateuser", ReplyAction="http://tempuri.org/ITechno_service/updateuserResponse")]
        bool updateuser(FinalWeb.TechService.User user, int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechno_service/updateuser", ReplyAction="http://tempuri.org/ITechno_service/updateuserResponse")]
        System.Threading.Tasks.Task<bool> updateuserAsync(FinalWeb.TechService.User user, int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechno_service/search_by_cat", ReplyAction="http://tempuri.org/ITechno_service/search_by_catResponse")]
        FinalWeb.TechService.ProductD[] search_by_cat(string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechno_service/search_by_cat", ReplyAction="http://tempuri.org/ITechno_service/search_by_catResponse")]
        System.Threading.Tasks.Task<FinalWeb.TechService.ProductD[]> search_by_catAsync(string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechno_service/search_by_price", ReplyAction="http://tempuri.org/ITechno_service/search_by_priceResponse")]
        FinalWeb.TechService.ProductD[] search_by_price(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechno_service/search_by_price", ReplyAction="http://tempuri.org/ITechno_service/search_by_priceResponse")]
        System.Threading.Tasks.Task<FinalWeb.TechService.ProductD[]> search_by_priceAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechno_service/productinfor_retrieval_ID", ReplyAction="http://tempuri.org/ITechno_service/productinfor_retrieval_IDResponse")]
        FinalWeb.TechService.ProductD productinfor_retrieval_ID(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechno_service/productinfor_retrieval_ID", ReplyAction="http://tempuri.org/ITechno_service/productinfor_retrieval_IDResponse")]
        System.Threading.Tasks.Task<FinalWeb.TechService.ProductD> productinfor_retrieval_IDAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechno_service/productinfor_retrieval_Name", ReplyAction="http://tempuri.org/ITechno_service/productinfor_retrieval_NameResponse")]
        FinalWeb.TechService.ProductD productinfor_retrieval_Name(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechno_service/productinfor_retrieval_Name", ReplyAction="http://tempuri.org/ITechno_service/productinfor_retrieval_NameResponse")]
        System.Threading.Tasks.Task<FinalWeb.TechService.ProductD> productinfor_retrieval_NameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechno_service/price_by_ASC", ReplyAction="http://tempuri.org/ITechno_service/price_by_ASCResponse")]
        FinalWeb.TechService.ProductD[] price_by_ASC(string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechno_service/price_by_ASC", ReplyAction="http://tempuri.org/ITechno_service/price_by_ASCResponse")]
        System.Threading.Tasks.Task<FinalWeb.TechService.ProductD[]> price_by_ASCAsync(string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechno_service/price_by_DESC", ReplyAction="http://tempuri.org/ITechno_service/price_by_DESCResponse")]
        FinalWeb.TechService.ProductD[] price_by_DESC(string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechno_service/price_by_DESC", ReplyAction="http://tempuri.org/ITechno_service/price_by_DESCResponse")]
        System.Threading.Tasks.Task<FinalWeb.TechService.ProductD[]> price_by_DESCAsync(string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechno_service/allProducts", ReplyAction="http://tempuri.org/ITechno_service/allProductsResponse")]
        FinalWeb.TechService.ProductD[] allProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechno_service/allProducts", ReplyAction="http://tempuri.org/ITechno_service/allProductsResponse")]
        System.Threading.Tasks.Task<FinalWeb.TechService.ProductD[]> allProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechno_service/RangePrice", ReplyAction="http://tempuri.org/ITechno_service/RangePriceResponse")]
        FinalWeb.TechService.ProductD[] RangePrice(int min, int max);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechno_service/RangePrice", ReplyAction="http://tempuri.org/ITechno_service/RangePriceResponse")]
        System.Threading.Tasks.Task<FinalWeb.TechService.ProductD[]> RangePriceAsync(int min, int max);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechno_service/FiltCatPrice", ReplyAction="http://tempuri.org/ITechno_service/FiltCatPriceResponse")]
        FinalWeb.TechService.ProductD[] FiltCatPrice(string Category, double price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechno_service/FiltCatPrice", ReplyAction="http://tempuri.org/ITechno_service/FiltCatPriceResponse")]
        System.Threading.Tasks.Task<FinalWeb.TechService.ProductD[]> FiltCatPriceAsync(string Category, double price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechno_service/Add_to_Cart", ReplyAction="http://tempuri.org/ITechno_service/Add_to_CartResponse")]
        bool Add_to_Cart(FinalWeb.TechService.ProductD product, int userID, int Qty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechno_service/Add_to_Cart", ReplyAction="http://tempuri.org/ITechno_service/Add_to_CartResponse")]
        System.Threading.Tasks.Task<bool> Add_to_CartAsync(FinalWeb.TechService.ProductD product, int userID, int Qty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechno_service/getUser_Cart", ReplyAction="http://tempuri.org/ITechno_service/getUser_CartResponse")]
        FinalWeb.TechService.CartClass[] getUser_Cart(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechno_service/getUser_Cart", ReplyAction="http://tempuri.org/ITechno_service/getUser_CartResponse")]
        System.Threading.Tasks.Task<FinalWeb.TechService.CartClass[]> getUser_CartAsync(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechno_service/payment", ReplyAction="http://tempuri.org/ITechno_service/paymentResponse")]
        bool payment(string type, System.DateTime date, decimal Amount, int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechno_service/payment", ReplyAction="http://tempuri.org/ITechno_service/paymentResponse")]
        System.Threading.Tasks.Task<bool> paymentAsync(string type, System.DateTime date, decimal Amount, int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechno_service/removeItem", ReplyAction="http://tempuri.org/ITechno_service/removeItemResponse")]
        bool removeItem(int userId, int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechno_service/removeItem", ReplyAction="http://tempuri.org/ITechno_service/removeItemResponse")]
        System.Threading.Tasks.Task<bool> removeItemAsync(int userId, int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechno_service/increaseQue", ReplyAction="http://tempuri.org/ITechno_service/increaseQueResponse")]
        bool increaseQue(int productId, int UserId, int num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechno_service/increaseQue", ReplyAction="http://tempuri.org/ITechno_service/increaseQueResponse")]
        System.Threading.Tasks.Task<bool> increaseQueAsync(int productId, int UserId, int num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechno_service/AddProduct", ReplyAction="http://tempuri.org/ITechno_service/AddProductResponse")]
        int AddProduct(FinalWeb.TechService.ProductD addP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechno_service/AddProduct", ReplyAction="http://tempuri.org/ITechno_service/AddProductResponse")]
        System.Threading.Tasks.Task<int> AddProductAsync(FinalWeb.TechService.ProductD addP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechno_service/EditProduct", ReplyAction="http://tempuri.org/ITechno_service/EditProductResponse")]
        int EditProduct(FinalWeb.TechService.ProductD pr, int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechno_service/EditProduct", ReplyAction="http://tempuri.org/ITechno_service/EditProductResponse")]
        System.Threading.Tasks.Task<int> EditProductAsync(FinalWeb.TechService.ProductD pr, int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechno_service/productinfor", ReplyAction="http://tempuri.org/ITechno_service/productinforResponse")]
        FinalWeb.TechService.ProductD productinfor(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechno_service/productinfor", ReplyAction="http://tempuri.org/ITechno_service/productinforResponse")]
        System.Threading.Tasks.Task<FinalWeb.TechService.ProductD> productinforAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechno_service/search_by_dis", ReplyAction="http://tempuri.org/ITechno_service/search_by_disResponse")]
        FinalWeb.TechService.ProductD[] search_by_dis();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechno_service/search_by_dis", ReplyAction="http://tempuri.org/ITechno_service/search_by_disResponse")]
        System.Threading.Tasks.Task<FinalWeb.TechService.ProductD[]> search_by_disAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechno_service/CountProduct", ReplyAction="http://tempuri.org/ITechno_service/CountProductResponse")]
        int CountProduct();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechno_service/CountProduct", ReplyAction="http://tempuri.org/ITechno_service/CountProductResponse")]
        System.Threading.Tasks.Task<int> CountProductAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechno_service/CountUser", ReplyAction="http://tempuri.org/ITechno_service/CountUserResponse")]
        int CountUser();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechno_service/CountUser", ReplyAction="http://tempuri.org/ITechno_service/CountUserResponse")]
        System.Threading.Tasks.Task<int> CountUserAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechno_service/CountSales", ReplyAction="http://tempuri.org/ITechno_service/CountSalesResponse")]
        int CountSales();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechno_service/CountSales", ReplyAction="http://tempuri.org/ITechno_service/CountSalesResponse")]
        System.Threading.Tasks.Task<int> CountSalesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITechno_serviceChannel : FinalWeb.TechService.ITechno_service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Techno_serviceClient : System.ServiceModel.ClientBase<FinalWeb.TechService.ITechno_service>, FinalWeb.TechService.ITechno_service {
        
        public Techno_serviceClient() {
        }
        
        public Techno_serviceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Techno_serviceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Techno_serviceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Techno_serviceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool UserRegister(FinalWeb.TechService.User user) {
            return base.Channel.UserRegister(user);
        }
        
        public System.Threading.Tasks.Task<bool> UserRegisterAsync(FinalWeb.TechService.User user) {
            return base.Channel.UserRegisterAsync(user);
        }
        
        public bool Login(string email, string password) {
            return base.Channel.Login(email, password);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(string email, string password) {
            return base.Channel.LoginAsync(email, password);
        }
        
        public FinalWeb.TechService.User userinfor_Retrieval(int ID) {
            return base.Channel.userinfor_Retrieval(ID);
        }
        
        public System.Threading.Tasks.Task<FinalWeb.TechService.User> userinfor_RetrievalAsync(int ID) {
            return base.Channel.userinfor_RetrievalAsync(ID);
        }
        
        public FinalWeb.TechService.User userinfor_Retrieval_Email(string email) {
            return base.Channel.userinfor_Retrieval_Email(email);
        }
        
        public System.Threading.Tasks.Task<FinalWeb.TechService.User> userinfor_Retrieval_EmailAsync(string email) {
            return base.Channel.userinfor_Retrieval_EmailAsync(email);
        }
        
        public bool resetPass(int email, string password) {
            return base.Channel.resetPass(email, password);
        }
        
        public System.Threading.Tasks.Task<bool> resetPassAsync(int email, string password) {
            return base.Channel.resetPassAsync(email, password);
        }
        
        public bool updateuser(FinalWeb.TechService.User user, int Id) {
            return base.Channel.updateuser(user, Id);
        }
        
        public System.Threading.Tasks.Task<bool> updateuserAsync(FinalWeb.TechService.User user, int Id) {
            return base.Channel.updateuserAsync(user, Id);
        }
        
        public FinalWeb.TechService.ProductD[] search_by_cat(string category) {
            return base.Channel.search_by_cat(category);
        }
        
        public System.Threading.Tasks.Task<FinalWeb.TechService.ProductD[]> search_by_catAsync(string category) {
            return base.Channel.search_by_catAsync(category);
        }
        
        public FinalWeb.TechService.ProductD[] search_by_price(string value) {
            return base.Channel.search_by_price(value);
        }
        
        public System.Threading.Tasks.Task<FinalWeb.TechService.ProductD[]> search_by_priceAsync(string value) {
            return base.Channel.search_by_priceAsync(value);
        }
        
        public FinalWeb.TechService.ProductD productinfor_retrieval_ID(int ID) {
            return base.Channel.productinfor_retrieval_ID(ID);
        }
        
        public System.Threading.Tasks.Task<FinalWeb.TechService.ProductD> productinfor_retrieval_IDAsync(int ID) {
            return base.Channel.productinfor_retrieval_IDAsync(ID);
        }
        
        public FinalWeb.TechService.ProductD productinfor_retrieval_Name(string name) {
            return base.Channel.productinfor_retrieval_Name(name);
        }
        
        public System.Threading.Tasks.Task<FinalWeb.TechService.ProductD> productinfor_retrieval_NameAsync(string name) {
            return base.Channel.productinfor_retrieval_NameAsync(name);
        }
        
        public FinalWeb.TechService.ProductD[] price_by_ASC(string category) {
            return base.Channel.price_by_ASC(category);
        }
        
        public System.Threading.Tasks.Task<FinalWeb.TechService.ProductD[]> price_by_ASCAsync(string category) {
            return base.Channel.price_by_ASCAsync(category);
        }
        
        public FinalWeb.TechService.ProductD[] price_by_DESC(string category) {
            return base.Channel.price_by_DESC(category);
        }
        
        public System.Threading.Tasks.Task<FinalWeb.TechService.ProductD[]> price_by_DESCAsync(string category) {
            return base.Channel.price_by_DESCAsync(category);
        }
        
        public FinalWeb.TechService.ProductD[] allProducts() {
            return base.Channel.allProducts();
        }
        
        public System.Threading.Tasks.Task<FinalWeb.TechService.ProductD[]> allProductsAsync() {
            return base.Channel.allProductsAsync();
        }
        
        public FinalWeb.TechService.ProductD[] RangePrice(int min, int max) {
            return base.Channel.RangePrice(min, max);
        }
        
        public System.Threading.Tasks.Task<FinalWeb.TechService.ProductD[]> RangePriceAsync(int min, int max) {
            return base.Channel.RangePriceAsync(min, max);
        }
        
        public FinalWeb.TechService.ProductD[] FiltCatPrice(string Category, double price) {
            return base.Channel.FiltCatPrice(Category, price);
        }
        
        public System.Threading.Tasks.Task<FinalWeb.TechService.ProductD[]> FiltCatPriceAsync(string Category, double price) {
            return base.Channel.FiltCatPriceAsync(Category, price);
        }
        
        public bool Add_to_Cart(FinalWeb.TechService.ProductD product, int userID, int Qty) {
            return base.Channel.Add_to_Cart(product, userID, Qty);
        }
        
        public System.Threading.Tasks.Task<bool> Add_to_CartAsync(FinalWeb.TechService.ProductD product, int userID, int Qty) {
            return base.Channel.Add_to_CartAsync(product, userID, Qty);
        }
        
        public FinalWeb.TechService.CartClass[] getUser_Cart(int userID) {
            return base.Channel.getUser_Cart(userID);
        }
        
        public System.Threading.Tasks.Task<FinalWeb.TechService.CartClass[]> getUser_CartAsync(int userID) {
            return base.Channel.getUser_CartAsync(userID);
        }
        
        public bool payment(string type, System.DateTime date, decimal Amount, int userID) {
            return base.Channel.payment(type, date, Amount, userID);
        }
        
        public System.Threading.Tasks.Task<bool> paymentAsync(string type, System.DateTime date, decimal Amount, int userID) {
            return base.Channel.paymentAsync(type, date, Amount, userID);
        }
        
        public bool removeItem(int userId, int productId) {
            return base.Channel.removeItem(userId, productId);
        }
        
        public System.Threading.Tasks.Task<bool> removeItemAsync(int userId, int productId) {
            return base.Channel.removeItemAsync(userId, productId);
        }
        
        public bool increaseQue(int productId, int UserId, int num) {
            return base.Channel.increaseQue(productId, UserId, num);
        }
        
        public System.Threading.Tasks.Task<bool> increaseQueAsync(int productId, int UserId, int num) {
            return base.Channel.increaseQueAsync(productId, UserId, num);
        }
        
        public int AddProduct(FinalWeb.TechService.ProductD addP) {
            return base.Channel.AddProduct(addP);
        }
        
        public System.Threading.Tasks.Task<int> AddProductAsync(FinalWeb.TechService.ProductD addP) {
            return base.Channel.AddProductAsync(addP);
        }
        
        public int EditProduct(FinalWeb.TechService.ProductD pr, int ID) {
            return base.Channel.EditProduct(pr, ID);
        }
        
        public System.Threading.Tasks.Task<int> EditProductAsync(FinalWeb.TechService.ProductD pr, int ID) {
            return base.Channel.EditProductAsync(pr, ID);
        }
        
        public FinalWeb.TechService.ProductD productinfor(int ID) {
            return base.Channel.productinfor(ID);
        }
        
        public System.Threading.Tasks.Task<FinalWeb.TechService.ProductD> productinforAsync(int ID) {
            return base.Channel.productinforAsync(ID);
        }
        
        public FinalWeb.TechService.ProductD[] search_by_dis() {
            return base.Channel.search_by_dis();
        }
        
        public System.Threading.Tasks.Task<FinalWeb.TechService.ProductD[]> search_by_disAsync() {
            return base.Channel.search_by_disAsync();
        }
        
        public int CountProduct() {
            return base.Channel.CountProduct();
        }
        
        public System.Threading.Tasks.Task<int> CountProductAsync() {
            return base.Channel.CountProductAsync();
        }
        
        public int CountUser() {
            return base.Channel.CountUser();
        }
        
        public System.Threading.Tasks.Task<int> CountUserAsync() {
            return base.Channel.CountUserAsync();
        }
        
        public int CountSales() {
            return base.Channel.CountSales();
        }
        
        public System.Threading.Tasks.Task<int> CountSalesAsync() {
            return base.Channel.CountSalesAsync();
        }
    }
}
